version: '3.8'

services:


  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped