"""create relationship

Revision ID: 86600dab4158
Revises: f7ffbd25fe94
Create Date: 2025-03-06 13:30:34.133325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86600dab4158"
down_revision: Union[str, None] = "f7ffbd25fe94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("order_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "products", "orders", ["order_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "order_id")
    # ### end Alembic commands ###
