"""create users and orders relationship

Revision ID: 9c6f39dd46b4
Revises: 92565ca80036
Create Date: 2025-03-07 12:21:19.179640

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c6f39dd46b4"
down_revision: Union[str, None] = "92565ca80036"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "orders", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "user_id")
    # ### end Alembic commands ###
